#!/usr/bin/env python3
"""Generate Agent Ops index.md from active operating thought frontmatter.

The operating thought pages are canonical. index.md is a deterministic retrieval view.
Every declared consult_when and do_not_use_when trigger must appear; there is no
positional cutoff. Active pages must live in a routed family directory.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPERATING_THOUGHT = ROOT / "operating-thought"
INDEX = ROOT / "index.md"
FAMILY_ORDER = ["authority", "knowledge", "decisions", "design", "capabilities"]
FAMILY_TITLES = {
    "authority": "Authority, approval, and access",
    "knowledge": "Information placement and source authority",
    "decisions": "Decision quality and strategic response",
    "design": "Architecture, change, and documentation",
    "capabilities": "External capabilities and integrations",
}


def parse_frontmatter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    try:
        block = text.split("---\n", 2)[1]
    except IndexError as exc:
        raise ValueError(f"{path}: malformed frontmatter") from exc
    data: dict[str, object] = {}
    current: str | None = None
    for raw in block.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        m = re.match(r"^([a-z_]+):(?:\s*(.*))?$", raw)
        if m:
            key, value = m.groups()
            current = key
            data[key] = value.strip().strip('"') if value and value.strip() else []
            continue
        m = re.match(r"^\s{2}-\s+(.*)$", raw)
        if m and current:
            if not isinstance(data[current], list):
                data[current] = []
            data[current].append(m.group(1).strip().strip('"'))
    return data


def items(value: object) -> list[str]:
    if isinstance(value, list):
        return [str(v) for v in value]
    if value:
        return [str(value)]
    return []


def discover_active_pages(
    root: Path | None = None,
) -> tuple[list[tuple[str, Path, dict[str, object]]], list[Path]]:
    """Return routed (family, path, meta) pages and active pages outside FAMILY_ORDER."""
    root = root or ROOT
    routed: list[tuple[str, Path, dict[str, object]]] = []
    unknown: list[Path] = []
    operating_thought = root / "operating-thought"
    if not operating_thought.is_dir():
        return routed, unknown
    for path in sorted(operating_thought.rglob("*.md")):
        meta = parse_frontmatter(path)
        if meta.get("status") != "active":
            continue
        rel = path.relative_to(operating_thought)
        if len(rel.parts) != 2 or rel.parts[0] not in FAMILY_ORDER:
            unknown.append(path)
            continue
        routed.append((rel.parts[0], path, meta))
    return routed, unknown


def join_triggers(values: list[str]) -> str:
    if not values:
        return ""
    text = "; ".join(values)
    if not text.endswith("."):
        text += "."
    return text


def page_block(root: Path, path: Path, meta: dict[str, object]) -> str:
    title = str(meta.get("title") or path.stem.replace("-", " ").title())
    summary = str(meta.get("router_summary") or "")
    consult = items(meta.get("consult_when"))
    skip = items(meta.get("do_not_use_when"))
    rel = path.relative_to(root).as_posix()
    block = [f"### [{title}]({rel})"]
    if summary:
        block.append(summary)
    if consult:
        block.append("**Consult when:** " + join_triggers(consult))
    if skip:
        block.append("**Do not use when:** " + join_triggers(skip))
    return "\n\n".join(block)


def render(root: Path | None = None) -> str:
    root = root or ROOT
    routed, unknown = discover_active_pages(root)
    if unknown:
        names = ", ".join(path.relative_to(root).as_posix() for path in unknown)
        raise ValueError(
            "active operating thought is not in a routed family: " + names
        )
    by_family: dict[str, list[str]] = {family: [] for family in FAMILY_ORDER}
    for family, path, meta in routed:
        by_family[family].append(page_block(root, path, meta))
    sections = [
        f"## {FAMILY_TITLES[family]}\n\n" + "\n\n".join(by_family[family])
        for family in FAMILY_ORDER
        if by_family[family]
    ]
    preamble = """# Agent Ops router

> Generated by `scripts/generate_index.py` from active operating thought frontmatter. Do not edit this file by hand.

Agent Ops is the agent's retrievable operating judgment. It is not a second SOUL, a tool inventory, or an encyclopedia.

## Router use

Persistent SOUL owns activation and re-entry behavior. Use the boundary map below when the exact owner is not already current. This generated view routes owner selection; it does not own activation.

## Boundary routing

- **Representation** → [Information Placement and Source Authority](operating-thought/knowledge/information-placement-and-source-authority.md) + domain skill — do not promote unknown to zero/false.
- **Causal inference** → [Decision Quality Under Uncertainty](operating-thought/decisions/decision-quality-under-uncertainty.md) + diagnostic skill — do not promote observation to cause.
- **Authority/effect** → [Permissions, Controls, and Discretion](operating-thought/authority/permissions-controls-and-discretion.md) + acting skill — capability is not authority; acknowledgement is not effect.
- **Outcome verification** → `artifact-verification` — do not promote tool success to user-visible success.
- **Correction** → source analysis and the canonical owner — repair dependent claims, artifacts, actions, and records.
- **Retention/stopping** → [Right-Sized Change](operating-thought/design/right-sized-change.md) + canonical owner — do not retain or compose machinery without material decision or acceptance value.

"""
    return preamble + "\n\n".join(sections) + "\n"


def coverage_errors(root: Path | None = None) -> list[str]:
    """Fail if an active page or declared trigger is missing from the generated router."""
    root = root or ROOT
    index_path = root / "index.md"
    index_text = index_path.read_text(encoding="utf-8") if index_path.is_file() else ""
    errors: list[str] = []
    routed, unknown = discover_active_pages(root)
    for path in unknown:
        errors.append(
            "active operating thought is not in a routed family: "
            + path.relative_to(root).as_posix()
        )
    for family, path, meta in routed:
        rel = path.relative_to(root).as_posix()
        if rel not in index_text:
            errors.append(f"router omitted active page: {rel}")
        for kind, key in (("consult", "consult_when"), ("skip", "do_not_use_when")):
            for item in items(meta.get(key)):
                if item not in index_text:
                    errors.append(f"router omitted {kind} trigger from {rel}: {item}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        generated = render()
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != generated:
            print("index.md is stale; run scripts/generate_index.py", file=sys.stderr)
            return 1
        print("index.md matches active operating thought frontmatter")
        return 0
    INDEX.write_text(generated, encoding="utf-8")
    print(f"wrote {INDEX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
